version: '3.8'
services:
  movies:
    image: prosenjitdey/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: prosenjitdey:train:latest
    ports:
      - "82:80"
    deploy:
      resplicas: 3

  paytm:
    image: prosenjitdey:paytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
